//! models/user.js

/**
 * Users model (queries only)
 * --------------------------
 * Keep this file limited to SQL queries. No business logic.
 */

import crypto from 'crypto';
import db from '../config/database.js';

// Fields safe to expose in req.user / views
const PUBLIC_FIELDS = `
	id,
	username,
	email,
	google_id,
	github_id,
	is_blocked,
	is_active,
	is_verified,
	visibility_status,
	last_login_at,
	created_at,
	updated_at
`;

// Sensitive fields (auth only)
const AUTH_FIELDS = `
	hashed_password,
	bad_login_attempts,
	token_hash,
	token_expires_at,
	token_request_count
`;

/**
 * Find a user by a supported key (safe allowlist)
 * @param {'id'|'email'|'username'|'googleId'|'githubId'} by
 * @param {string} value
 * @param {{ withAuth?: boolean }} [options]
 * @returns {Promise<object|null>}
 */
async function findUserBy(by, value, { withAuth = false } = {}) {
	const columnBy = {
		id: 'id',
		email: 'email',
		username: 'username',
		googleId: 'google_id',
		githubId: 'github_id',
	};

	const column = columnBy[by];
	if (!column) {
		throw new Error(`Unsupported lookup key: ${by}`);
	}

	const fields = withAuth
		? `${PUBLIC_FIELDS}, ${AUTH_FIELDS}`
		: PUBLIC_FIELDS;

	const [rows] = await db.query(
		`SELECT ${fields}
		 FROM users
		 WHERE ${column} = ?
		 LIMIT 1`,
		[value]
	);

	return rows[0] ?? null;
}

/**
 * Link OAuth provider IDs to an existing user
 * @param {string} userId
 * @param {Object} providers
 * @param {string} [providers.googleId]
 * @param {string} [providers.githubId]
 */
async function linkOAuthId(userId, { googleId, githubId }) {
	const fields = [];
	const values = [];

	if (googleId) {
		fields.push('google_id = ?');
		values.push(googleId);
	}

	if (githubId) {
		fields.push('github_id = ?');
		values.push(githubId);
	}

	// Nothing to update → no-op
	if (fields.length === 0) return;

	values.push(userId);

	await db.query(
		`UPDATE users
		 SET ${fields.join(', ')}
		 WHERE id = ?
		 LIMIT 1`,
		values
	);
}

async function createOAuthUser({ email, googleId = null, githubId = null }) {
	const id = crypto.randomUUID();

	const columns = [
		'id',
		'email',
		'is_active',
		'is_verified',
		'google_id',
		'github_id',
	];
	const placeholders = ['?', '?', 'TRUE', 'TRUE', '?', '?'];
	const values = [id, email, googleId, githubId];

	await db.query(
		`INSERT INTO users (${columns.join(', ')})
		 VALUES (${placeholders.join(', ')})`,
		values
	);

	return findUserBy('id', id);
}

/**
 * Create a pending user (email-first registration)
 * ------------------------------------------------
 * Creates a user record with:
 * - email set
 * - username/password empty
 * - verified = false
 * - active = true (account exists, but not verified yet)
 *
 * @param {{ email: string }} params
 * @returns {Promise<string>} userId (UUID)
 */
async function createPendingUser({ email }) {
	try {
		await db.query(
			`INSERT INTO users (
			email,
			is_active,
			is_verified
		) VALUES (?, TRUE, FALSE)`,
			[email]
		);
	} catch (err) {
		if (err.code !== 'ER_DUP_ENTRY') throw err;
	}

	// When id is generated by UUID() default, mysql2 result doesn't contain it.
	// So fetch it back by email (email is unique).
	const user = await findUserBy('email', email);
	return user.id;
}

/**
 * Set signup token hash + expiry for email-first registration
 * ----------------------------------------------------------
 * Stores only the HASH of the token (never the raw token).
 * Also increments token_request_count for rate limiting/abuse detection.
 *
 * @param {{ userId: string, tokenHash: string, tokenExpiresAt: Date }} params
 * @returns {Promise<void>}
 */
async function setSignupToken({ userId, tokenHash, tokenExpiresAt }) {
	await db.query(
		`UPDATE users
		 SET
			token_hash = ?,
			token_expires_at = ?,
			token_request_count = token_request_count + 1
		 WHERE id = ?
		 LIMIT 1`,
		[tokenHash, tokenExpiresAt, userId]
	);
}

/**
 * Find user by signup token hash
 * ------------------------------
 * Used to validate the email-first registration token.
 * Returns minimal fields required to validate and complete signup.
 *
 * @param {string} tokenHash
 * @returns {Promise<object|null>}
 */
async function findBySignupTokenHash(tokenHash) {
	const [rows] = await db.query(
		`SELECT
			id,
			email,
			token_expires_at
		 FROM users
		 WHERE token_hash = ?
		 LIMIT 1`,
		[tokenHash]
	);

	return rows[0] ?? null;
}

/**
 * Complete signup (username + password)
 * -------------------------------------
 * Finalizes a pending account by:
 * - setting username
 * - setting hashed password
 * - marking verified = true
 * - clearing token fields (one-time use)
 *
 * @param {{ userId: string, username: string, hashedPassword: string }} params
 * @returns {Promise<void>}
 */
async function completeSignup({ userId, username, hashedPassword }) {
	await db.query(
		`UPDATE users
		 SET
			username = ?,
			hashed_password = ?,
			is_verified = TRUE,
			token_hash = NULL,
			token_expires_at = NULL,
			token_request_count = 0
		 WHERE id = ?
		 LIMIT 1`,
		[username, hashedPassword, userId]
	);
}

export default {
	findUserBy,
	createOAuthUser,
	linkOAuthId,
	createPendingUser,
	setSignupToken,
	findBySignupTokenHash,
	completeSignup,
};
